Repository maketheworldwise/sensor-admin-react-bodit, pull requests merged in 2022-10, with the labels that each got.

#8 Feature: 테이블 UI 및 정렬 기능 구현
  package-lock.json
  package.json
  src/Pages/Sensor/Api.js
  src/Pages/Sensor/Sensor.js
  src/Pages/Sensor/Sensor.module.scss
  src/Pages/Sensor/columns.js
Labels: 💄 UI, ✨ Feature

#9 UI - 습도그래프 추가 및 각각 그래프 타이틀 추가
  package-lock.json
  src/Pages/Graph/Graph.js
  src/Pages/Graph/Graph.module.scss
  src/Pages/Graph/Humidity.js
Labels: 💄 UI, ✨ Feature

#10 Modify: calendar 날짜 클릭시 차트 아웃
  package-lock.json
  package.json
  src/Pages/Calendar/Calendar.js
  src/Pages/Calendar/Calendar.module.scss
  src/Pages/Graph/Graph.js
  src/Router.js
Labels: 💄 UI, 🎨 Modify

#11 Add: pressure 그래프 추가
  src/Pages/Graph/Graph.js
  src/Pages/Graph/Pressure.js
Labels: ✨ Feature
